// Haltbarkeit tiefgefroren (bei konstant -18 °C). Die Monatsangaben sind reine
// Qualitätsempfehlungen (Geschmack/Textur) – laut USDA/FSIS ist tiefgekühltes
// Essen bei -18 °C durchgehend SICHER, unabhängig von der Lagerdauer.
//
// Gleiches Muster wie openedShelfLife.js: erster Substring-Treffer auf den
// kleingeschriebenen Namen gewinnt, Spezifisches vor Allgemeinem. `category`
// dient NUR der Anzeige (Gruppierung im Ratgeber) und darf die Matching-
// Reihenfolge oben nicht beeinflussen. Jeder Eintrag ist recherchiert (u.a.
// USDA FSIS, Verbraucherzentrale, Alnatura, Initiative Tierwohl) – keine
// erfundenen Angaben. Phase 1: 13 gut abgesicherte Kernartikel, Schwerpunkt
// Fleisch/Wurst, Käse, Brot. Phase 2: 6 weitere Artikel (Fisch, Milch/Sahne,
// Kräuter, Teig).
//
// `notRecommended: true` statt `months`, wenn Einfrieren grundsätzlich nicht
// empfohlen wird (z.B. Weich-/Frischkäse wird krümelig/wässrig).

export const FROZEN_SHELF_RULES = [
  { keys: ['hackfleisch', 'hackepeter', 'schabefleisch', 'tatar', 'mett'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Hackfleisch / Mett (roh)', label_en: 'Ground meat (raw)', months: 3, prep: null, prep_en: null, reason: 'Große Oberfläche, hohe Keimlast – Qualität und Sicherheit sinken nach dem Auftauen schneller als bei Braten/Steaks.', reason_en: 'Large surface area, high bacterial load – quality and safety decline faster after thawing than with roasts/steaks.' },
  { keys: ['hähnchen', 'haehnchen', 'hühner', 'huhn', 'pute', 'geflügel', 'gefluegel'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Geflügel (roh)', label_en: 'Poultry (raw)', months: 10, prep: null, prep_en: null, reason: 'Ganz oder in Teilen gut einfrierbar; ganzes Geflügel hält sich tendenziell etwas länger als einzelne Teile.', reason_en: 'Freezes well whole or in parts; whole poultry tends to keep a bit longer than individual pieces.' },
  { keys: ['schnitzel', 'gulasch', 'steak', 'filet', 'kotelett', 'braten', 'rinderbraten', 'schweinebraten', 'fleisch'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Rotes Fleisch (roh, Braten/Steak)', label_en: 'Red meat (raw, roast/steak)', months: 8, prep: null, prep_en: null, reason: 'Rind/Schwein roh eingefroren hält sich je nach Stück 6-12 Monate; Qualität nimmt danach graduell ab.', reason_en: 'Beef/pork frozen raw keeps 6-12 months depending on the cut; quality gradually declines after that.' },
  { keys: ['lachs', 'hering', 'makrele', 'thunfisch', 'thun'], category: 'Fisch & Meeresfrüchte', category_en: 'Fish & Seafood', label: 'Fettreicher Fisch (roh)', label_en: 'Fatty fish (raw)', months: 3, prep: null, prep_en: null, reason: 'Ungesättigte Fettsäuren oxidieren bei Minustemperaturen schneller als bei magerem Fisch – dadurch ranziger Geschmack nach längerer Lagerung.', reason_en: 'Unsaturated fatty acids oxidize faster at freezing temperatures than in lean fish – leading to a rancid taste after longer storage.' },
  { keys: ['kabeljau', 'seelachs', 'scholle', 'zander', 'forelle', 'pangasius', 'fisch'], category: 'Fisch & Meeresfrüchte', category_en: 'Fish & Seafood', label: 'Fettarmer Fisch (roh)', label_en: 'Lean fish (raw)', months: 6, prep: null, prep_en: null, reason: 'Fettarme Sorten oxidieren langsamer und bleiben länger geschmacklich stabil als fettreiche Fischarten. Nach dem Auftauen nicht erneut einfrieren.', reason_en: 'Lean varieties oxidize more slowly and stay stable in taste longer than fatty fish. Do not refreeze after thawing.' },
  { keys: ['aufschnitt', 'lyoner', 'mortadella', 'fleischwurst', 'bierschinken', 'kochschinken', 'gelbwurst', 'wiener', 'würstchen', 'wuerstchen', 'frankfurter', 'saitenwurst', 'schinken', 'wurst'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Aufschnitt / Brühwurst', label_en: 'Cold cuts / boiled sausage', months: 2, prep: null, prep_en: null, reason: 'In Originalverpackung eingefroren 1-3 Monate; vakuumiert deutlich länger. Nach dem Auftauen nicht erneut einfrieren.', reason_en: 'Frozen in original packaging keeps 1-3 months; vacuum-sealed considerably longer. Do not refreeze after thawing.' },
  { keys: ['salami', 'dauerwurst', 'cervelat', 'landjäger', 'landjaeger', 'chorizo', 'pepperoni', 'speck', 'bacon', 'rohschinken', 'serrano', 'parma', 'prosciutto'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Rohwurst / Speck', label_en: 'Cured sausage / bacon', months: 2, prep: null, prep_en: null, reason: 'Niedrigerer Wassergehalt als Brühwurst, aber ohne belastbare längere Richtwerte – konservativ wie Aufschnitt behandelt.', reason_en: 'Lower water content than boiled sausage, but without solid data for a longer guideline – treated conservatively like cold cuts.' },
  { keys: ['parmesan', 'grana', 'pecorino', 'bergkäse', 'hartkäse', 'emmentaler'], category: 'Käse', category_en: 'Cheese', label: 'Hartkäse', label_en: 'Hard cheese', months: 6, prep: 'Am besten gerieben einfrieren.', prep_en: 'Best frozen grated.', reason: 'Niedriger Wassergehalt – friert am verträglichsten von allen Käsesorten ein.', reason_en: 'Low water content – freezes best of all cheese types.' },
  { keys: ['frischkäse', 'streichkäse', 'philadelphia', 'doppelrahm', 'mozzarella', 'ricotta', 'feta', 'hirtenkäse', 'schafskäse', 'camembert', 'brie', 'blauschimmel', 'gorgonzola', 'roquefort'], category: 'Käse', category_en: 'Cheese', label: 'Weich- / Frischkäse', label_en: 'Soft / fresh cheese', months: null, notRecommended: true, prep: null, prep_en: null, reason: 'Hoher Wassergehalt – wird nach dem Auftauen krümelig, schmierig oder wässrig. Käse mit Schimmelrinde verändert zusätzlich Geschmack und Textur.', reason_en: 'High water content – becomes crumbly, greasy, or watery after thawing. Mold-rind cheeses also change in taste and texture.' },
  { keys: ['gouda', 'cheddar', 'edamer', 'tilsiter', 'butterkäse', 'maasdamer', 'appenzeller', 'raclette'], category: 'Käse', category_en: 'Cheese', label: 'Schnittkäse', label_en: 'Semi-hard cheese', months: 4, prep: 'Scheiben mit Butterbrotpapier trennen, damit sie nicht zusammenkleben.', prep_en: 'Separate slices with wax paper so they don\'t stick together.', reason: 'Fester als Weichkäse, aber etwas wasserreicher als Hartkäse – daher kürzere Frist.', reason_en: 'Firmer than soft cheese, but somewhat more watery than hard cheese – hence the shorter timeframe.' },
  { keys: ['butter', 'margarine'], category: 'Fette & Eier', category_en: 'Fats & Eggs', label: 'Butter / Margarine', label_en: 'Butter / margarine', months: 6, prep: null, prep_en: null, reason: 'Gesalzene Butter hält sich eingefroren tendenziell länger (bis 12 Monate) als ungesalzene.', reason_en: 'Salted butter tends to keep longer frozen (up to 12 months) than unsalted.' },
  { keys: ['sahne', 'obers'], category: 'Milchprodukte', category_en: 'Dairy', label: 'Sahne', label_en: 'Cream', months: 3, prep: 'Luftdicht verpacken, Kontakt mit anderen Lebensmitteln vermeiden; am besten über Nacht im Kühlschrank auftauen.', prep_en: 'Pack airtight, avoid contact with other foods; best thawed overnight in the fridge.', reason: 'Gilt sowohl für flüssige als auch für bereits geschlagene Sahne.', reason_en: 'Applies to both liquid and already-whipped cream.' },
  { keys: ['frischmilch', 'vollmilch', 'h-milch', 'milch'], category: 'Milchprodukte', category_en: 'Dairy', label: 'Milch', label_en: 'Milk', months: 3, prep: 'Nach dem Auftauen gut schütteln/verrühren.', prep_en: 'Shake/stir well after thawing.', reason: 'Fett und Wasser trennen sich beim Einfrieren – Konsistenz leidet, daher nur zum Kochen verwenden, nicht pur trinken.', reason_en: 'Fat and water separate when frozen – consistency suffers, so use only for cooking, not for drinking plain.' },
  { keys: ['brot', 'toast', 'brötchen', 'broetchen', 'baguette'], category: 'Backwaren & Teig', category_en: 'Baked Goods & Dough', label: 'Brot / Backwaren', label_en: 'Bread / baked goods', months: 3, prep: 'Vor dem Einfrieren auf Zimmertemperatur abkühlen lassen (sonst Kondensation).', prep_en: 'Let cool to room temperature before freezing (otherwise condensation forms).', reason: 'Aufgeschnitten/verpackt ca. 3 Monate; ein ganzer, unangeschnittener Laib hält sich auch bis zu 6 Monate.', reason_en: 'Sliced/packaged about 3 months; a whole, uncut loaf can also keep up to 6 months.' },
  { keys: ['blätterteig', 'blaetterteig', 'hefeteig', 'pizzateig'], category: 'Backwaren & Teig', category_en: 'Baked Goods & Dough', label: 'Teig (Blätter-/Hefeteig, roh)', label_en: 'Dough (puff/yeast, raw)', months: 6, prep: 'Blätterteig am besten industriell gekauft einfrieren (selbstgemacht eher 2-3 Monate); Hefeteig roh vor dem Gehen einfrieren; Pizzateig direkt im Beutel flach ausrollen, taut dann schneller auf.', prep_en: 'Store-bought puff pastry freezes best (homemade tends to keep 2-3 months); freeze yeast dough raw before it rises; roll pizza dough flat in the bag so it thaws faster.', reason: 'Roh eingefroren bleibt die Hefe im Ruhezustand und kann nach dem Auftauen ihre volle Arbeit verrichten.', reason_en: 'Frozen raw, the yeast stays dormant and can do its full work after thawing.' },
  { keys: ['erbsen', 'bohnen', 'brokkoli', 'blumenkohl', 'spinat', 'möhre', 'moehre', 'karotte', 'karotten', 'fenchel', 'kohlrabi', 'mangold', 'rosenkohl'], category: 'Obst & Gemüse', category_en: 'Fruit & Vegetables', label: 'Gemüse (blanchiert)', label_en: 'Vegetables (blanched)', months: 10, prep: 'Vorher blanchieren (3-5 Min. kochen, dann in Eiswasser abschrecken) – deaktiviert Enzyme, erhält Farbe und Vitamine.', prep_en: 'Blanch first (boil 3-5 min, then shock in ice water) – deactivates enzymes, preserves color and vitamins.', reason: 'Ohne Blanchieren verlieren diese Sorten beim Einfrieren deutlich an Farbe, Textur und Vitaminen.', reason_en: 'Without blanching, these vegetables lose significant color, texture, and vitamins when frozen.' },
  { keys: ['zucchini', 'paprika', 'pilz', 'champignon', 'spargel', 'kürbis', 'kuerbis', 'lauchzwiebel', 'frühlingszwiebel', 'fruehlingszwiebel'], category: 'Obst & Gemüse', category_en: 'Fruit & Vegetables', label: 'Gemüse (ohne Blanchieren)', label_en: 'Vegetables (no blanching)', months: 8, prep: null, prep_en: null, reason: 'Fester bzw. wasserärmer – kann roh eingefroren werden, kein Blanchieren nötig.', reason_en: 'Firmer or lower in water content – can be frozen raw, no blanching needed.' },
  { keys: ['schnittlauch', 'petersilie', 'dill', 'thymian', 'estragon', 'melisse', 'minze', 'basilikum', 'kräuter', 'kraeuter'], category: 'Kräuter', category_en: 'Herbs', label: 'Frische Kräuter', label_en: 'Fresh herbs', months: 10, prep: 'Gehackt in Eiswürfelbehältern mit etwas Wasser oder Öl einfrieren; Vakuumieren hält Aroma am besten.', prep_en: 'Freeze chopped in ice cube trays with a bit of water or oil; vacuum-sealing preserves aroma best.', reason: 'Bleiben so 6-12 Monate haltbar, verlieren aber über die Zeit zunehmend an Aroma – nach etwa einem Jahr oft schon spürbar schaler.', reason_en: 'Keeps this way for 6-12 months, but gradually loses aroma over time – often noticeably blander after about a year.' },
  { keys: ['beere', 'beeren', 'himbeere', 'himbeeren', 'heidelbeere', 'heidelbeeren', 'blaubeere', 'blaubeeren', 'erdbeere', 'erdbeeren', 'kirsche', 'kirschen', 'pfirsich', 'aprikose', 'apfel', 'äpfel', 'aepfel', 'birne', 'birnen', 'banane', 'bananen'], category: 'Obst & Gemüse', category_en: 'Fruit & Vegetables', label: 'Obst / Beeren', label_en: 'Fruit / berries', months: 10, prep: 'Beeren einzeln auf einem Blech vorfrieren (verhindert Verklumpen); Steinobst vorher entsteinen; Bananen geschält in Scheiben.', prep_en: 'Pre-freeze berries individually on a tray (prevents clumping); pit stone fruit first; freeze bananas peeled and sliced.', reason: 'Beeren und Steinobst bis zu 12 Monate, Apfel-/Birnenscheiben 8-10 Monate, Bananenscheiben eher 3-6 Monate.', reason_en: 'Berries and stone fruit up to 12 months, apple/pear slices 8-10 months, banana slices more like 3-6 months.' },
  { keys: ['suppe', 'eintopf', 'auflauf', 'fertiggericht', 'reste', 'soße', 'sosse', 'sauce', 'pasta', 'nudelgericht'], category: 'Fertiggerichte & Reste', category_en: 'Ready Meals & Leftovers', label: 'Reste / gekochte Gerichte', label_en: 'Leftovers / cooked dishes', months: 3, prep: 'Vor dem Einfrieren vollständig abkühlen lassen.', prep_en: 'Let cool completely before freezing.', reason: 'Gilt als grobe Richtschnur für die meisten gekochten Gerichte, Suppen und Saucen.', reason_en: 'A rough guideline for most cooked dishes, soups, and sauces.' },
];

// Passende Regel zum Namen (oder null) – erster Substring-Treffer gewinnt.
export function frozenRule(name) {
  const n = (name || '').toLowerCase();
  if (!n) return null;
  for (const r of FROZEN_SHELF_RULES) {
    if (r.keys.some((k) => n.includes(k))) return r;
  }
  return null;
}

// Info-Objekt für die Anzeige: { months, notRecommended, prep, reason, label, prep_en, reason_en, label_en } | null.
export function frozenInfo(name) {
  const r = frozenRule(name);
  if (!r) return null;
  return { months: r.months, notRecommended: !!r.notRecommended, prep: r.prep, reason: r.reason, label: r.label, prep_en: r.prep_en, reason_en: r.reason_en, label_en: r.label_en };
}
