// Obst-&-Gemüse-Lagerwissen: kühlen ja/nein, Ethylen-Verhalten (wer reift/
// verdirbt wen schneller), Verpackungshinweise. Gleiche Matching-Logik wie
// bei den Öffnen-Regeln in openedShelfLife.js (erster Substring-Treffer auf
// den kleingeschriebenen Namen gewinnt), gleiches storage-Vokabular
// ('fridge'|'room'|'both'), damit storageLabel()/storageMismatch()/
// zoneIsCooled() aus openedShelfLife.js direkt mitgenutzt werden können.
//
// ethyleneProduces/ethyleneSensitive: 'high'|'medium'|'low'|'none'. Kombinationen
// ("was zusammen/nicht zusammen lagern") werden bewusst nicht als starre
// Paar-Tabelle gepflegt, sondern ergeben sich aus diesen zwei Werten: ein
// hoher/mittlerer Ethylen-Produzent sollte nicht neben einer hoch/mittel
// empfindlichen Sorte liegen.
//
// Jeder Eintrag ist recherchiert (u.a. USDA/Extension-Quellen, Michigan
// State University Extension, UC Davis Postharvest Center) – keine
// erfundenen Angaben. Phase 1: 10 sehr gängige, gut abgesicherte Sorten.
// Phase 2: 13 weitere Sorten. Phase 3: 10 weitere Sorten (u.a. Kräuter).
// Phase 4: 10 weitere Sorten (Exoten, Beeren, mehr Kräuter/Gemüse).
//
// `category`: 'obst'|'gemuese'|'kraeuter' – fürs Filtern in der UI, hat
// keinen Einfluss auf die Lager-Logik (die richtet sich nur nach `storage`/
// `ethylene*`).
//
// `emoji`: optional, nur gesetzt wenn es ein wirklich passendes Symbol gibt
// (nicht erzwungen) – rein für die visuelle Trennung der Karten im Ratgeber.
//
// `label`/`reason`/`packaging` sind Deutsch, `label_en`/`reason_en`/
// `packaging_en` die Übersetzungen fürs englische UI (siehe lib/i18n.js).
// `keys` (fürs Matching auf den – immer noch deutschen – Artikelnamen)
// bleiben unverändert, unabhängig von der UI-Sprache.

import { tr } from './i18n.js';

export const PRODUCE_RULES = [
  {
    keys: ['apfel', 'äpfel', 'aepfel'],
    label: 'Apfel', label_en: 'Apple',
    category: 'obst',
    emoji: '🍎',
    storage: 'fridge',
    ethyleneProduces: 'high',
    ethyleneSensitive: 'low',
    packaging: 'Lose oder in perforierter Tüte im Kühlschrank, nicht luftdicht verpacken.',
    packaging_en: 'Loose or in a perforated bag in the fridge, don’t seal airtight.',
    reason: 'Setzt viel Ethylen frei – lässt anderes Obst/Gemüse in der Nähe schneller reifen bzw. verderben. Im Kühlschrank deutlich länger haltbar als bei Raumtemperatur.',
    reason_en: 'Releases a lot of ethylene – makes other fruit/veg nearby ripen or spoil faster. Keeps much longer in the fridge than at room temperature.',
  },
  {
    keys: ['banane', 'bananen'],
    label: 'Banane', label_en: 'Banana',
    category: 'obst',
    emoji: '🍌',
    storage: 'room',
    ethyleneProduces: 'high',
    ethyleneSensitive: 'medium',
    packaging: 'Lose bei Raumtemperatur lagern, nicht im Kühlschrank.',
    packaging_en: 'Store loose at room temperature, not in the fridge.',
    reason: 'Setzt sehr viel Ethylen frei – von anderem Obst/Gemüse fernhalten. Kühlschrank stoppt die Reifung und lässt die Schale braun/schwarz werden (die Frucht selbst bleibt meist noch genießbar).',
    reason_en: 'Releases very high amounts of ethylene – keep away from other fruit/veg. The fridge stops ripening and turns the peel brown/black (the fruit itself usually stays edible).',
  },
  {
    keys: ['tomate', 'tomaten'],
    label: 'Tomate', label_en: 'Tomato',
    category: 'gemuese',
    emoji: '🍅',
    storage: 'room',
    ethyleneProduces: 'high',
    ethyleneSensitive: 'low',
    packaging: 'Bei Raumtemperatur, Stielansatz nach unten, nicht luftdicht verpacken.',
    packaging_en: 'At room temperature, stem side down, don’t seal airtight.',
    reason: 'Kälte zerstört Aromastoffe – im Kühlschrank werden Tomaten mehlig und fad. Setzt selbst Ethylen frei, reift also andere Sorten in der Nähe schneller nach.',
    reason_en: 'Cold destroys aroma compounds – tomatoes turn mealy and bland in the fridge. Also releases ethylene itself, so it speeds up ripening of other produce nearby.',
  },
  {
    keys: ['kartoffel', 'kartoffeln'],
    label: 'Kartoffel', label_en: 'Potato',
    category: 'gemuese',
    emoji: '🥔',
    storage: 'room',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'Kühl, dunkel, trocken und luftig lagern (Papiertüte/Karton, nicht luftdicht in Plastik). Nicht neben Zwiebeln.',
    packaging_en: 'Store cool, dark, dry and airy (paper bag/box, not sealed in plastic). Not next to onions.',
    reason: 'Im Kühlschrank wandelt sich Stärke schneller in Zucker um (süßlich-körniger Geschmack, beim scharfen Braten/Frittieren mehr Acrylamid). Licht lässt sie grün werden und keimen – dunkel lagern. Getrennt von Zwiebeln, beide beschleunigen sich gegenseitig beim Verderben.',
    reason_en: 'In the fridge, starch converts to sugar faster (sweetish, grainy taste, more acrylamide when frying/roasting hot). Light makes them turn green and sprout – store in the dark. Keep away from onions, they speed up each other’s spoiling.',
  },
  {
    keys: ['zwiebel', 'zwiebeln'],
    label: 'Zwiebel', label_en: 'Onion',
    category: 'gemuese',
    emoji: '🧅',
    storage: 'room',
    ethyleneProduces: 'medium',
    ethyleneSensitive: 'medium',
    packaging: 'Kühl, dunkel, trocken und luftig lagern (Netz oder offener Korb, nicht in Plastik). Nicht neben Kartoffeln.',
    packaging_en: 'Store cool, dark, dry and airy (net or open basket, not in plastic). Not next to potatoes.',
    reason: 'Im Kühlschrank wandelt sich Stärke schneller in Zucker um, dadurch schnellerer Verderb. Setzt selbst Gase frei, die Kartoffeln in der Nähe schneller keimen lassen.',
    reason_en: 'In the fridge, starch converts to sugar faster, causing quicker spoilage. Also releases gases that make nearby potatoes sprout faster.',
  },
  {
    keys: ['karotte', 'karotten', 'möhre', 'moehre', 'möhren', 'moehren'],
    label: 'Karotte', label_en: 'Carrot',
    category: 'gemuese',
    emoji: '🥕',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'high',
    packaging: 'Im Kühlschrank, Laub/Grün abschneiden (entzieht sonst Feuchtigkeit), in perforierter Tüte oder feuchtem Tuch.',
    packaging_en: 'In the fridge, cut off any green tops (they draw out moisture otherwise), in a perforated bag or damp cloth.',
    reason: 'Sehr ethylenempfindlich – wird in der Nähe von Äpfeln, Bananen & Co. bitter (Bildung von Isocumarin). Getrennt von ethylenreichem Obst lagern.',
    reason_en: 'Very ethylene-sensitive – turns bitter near apples, bananas & co. (isocoumarin forms). Store away from ethylene-rich fruit.',
  },
  {
    keys: ['kopfsalat', 'eisbergsalat', 'salatkopf', 'salat'],
    label: 'Salat', label_en: 'Lettuce',
    category: 'gemuese',
    emoji: '🥬',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'high',
    packaging: 'Im Gemüsefach, locker in einer Tüte (nicht luftdicht), nicht neben Obst.',
    packaging_en: 'In the crisper drawer, loosely in a bag (not airtight), not next to fruit.',
    reason: 'Sehr ethylenempfindlich – bekommt braune Flecken (Russet Spotting), wenn es neben Äpfeln, Bananen oder Tomaten liegt.',
    reason_en: 'Very ethylene-sensitive – gets brown spots (russet spotting) when stored near apples, bananas or tomatoes.',
  },
  {
    keys: ['gurke', 'gurken', 'salatgurke'],
    label: 'Gurke', label_en: 'Cucumber',
    category: 'gemuese',
    emoji: '🥒',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'high',
    packaging: 'Im Gemüsefach am wärmeren Rand (nicht direkt an der Kühlwand), getrennt von Obst. Angeschnitten in Folie.',
    packaging_en: 'In the crisper drawer at the warmer edge (not directly against the cold wall), away from fruit. Once cut, wrap in film.',
    reason: 'Sehr ethylenempfindlich – wird schneller weich/gelb neben Obst. Zu kalt (unter ca. 10 °C) schadet zusätzlich (Kälteschäden), daher nicht ganz hinten/unten im Kühlschrank lagern.',
    reason_en: 'Very ethylene-sensitive – turns soft/yellow faster near fruit. Too cold (below about 10 °C/50 °F) also causes chill damage, so don’t store it at the very back/bottom of the fridge.',
  },
  {
    keys: ['zitrone', 'zitronen'],
    label: 'Zitrone', label_en: 'Lemon',
    category: 'obst',
    emoji: '🍋',
    storage: 'both',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'low',
    packaging: 'Unverpackt lagerbar. Im Kühlschrank (Gemüsefach) am längsten haltbar, bei Raumtemperatur nur für den kurzfristigen Verbrauch.',
    packaging_en: 'Can be stored unwrapped. Keeps longest in the fridge (crisper drawer); at room temperature only for short-term use.',
    reason: 'Bei Raumtemperatur nur wenige Tage haltbar, im Kühlschrank mehrere Wochen. Ethylen spielt bei Zitrusfrüchten eine geringere Rolle als bei anderem Obst.',
    reason_en: 'Keeps only a few days at room temperature, several weeks in the fridge. Ethylene plays a smaller role for citrus fruit than for other produce.',
  },
  {
    keys: ['avocado', 'avocados'],
    label: 'Avocado', label_en: 'Avocado',
    category: 'obst',
    emoji: '🥑',
    storage: 'both',
    ethyleneProduces: 'high',
    ethyleneSensitive: 'high',
    packaging: 'Unreif bei Raumtemperatur (in Papiertüte mit Apfel/Banane reift sie schneller). Reif: im Kühlschrank, das bremst die weitere Reifung.',
    packaging_en: 'Unripe: at room temperature (in a paper bag with an apple/banana to ripen faster). Ripe: in the fridge, which slows further ripening.',
    reason: 'Reagiert selbst stark auf Ethylen – reift in der Nähe von Äpfeln, Bananen oder Tomaten oft schneller als gewünscht. Setzt aber auch selbst viel Ethylen frei.',
    reason_en: 'Reacts strongly to ethylene itself – often ripens faster than desired near apples, bananas or tomatoes. Also releases a lot of ethylene itself.',
  },
  {
    keys: ['paprika'],
    label: 'Paprika', label_en: 'Bell pepper',
    category: 'gemuese',
    emoji: '🫑',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'low',
    packaging: 'Im Gemüsefach des Kühlschranks lagern, lose oder in perforierter Tüte.',
    packaging_en: 'Store in the fridge’s crisper drawer, loose or in a perforated bag.',
    reason: 'Kälteempfindlicher als andere Kühlschrank-Sorten – unterhalb von ca. 7 °C drohen Kälteschäden (Grübchen, beschleunigte Fäulnis). Im Gemüsefach (wärmster Bereich des Kühlschranks) am besten aufgehoben; bei Raumtemperatur nur 3-5 Tage haltbar.',
    reason_en: 'More cold-sensitive than other fridge produce – below about 7 °C/45 °F, chill damage (pitting, faster rot) can occur. Best kept in the crisper drawer (the fridge’s warmest zone); keeps only 3-5 days at room temperature.',
  },
  {
    keys: ['knoblauch'],
    label: 'Knoblauch', label_en: 'Garlic',
    category: 'gemuese',
    emoji: '🧄',
    storage: 'room',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'low',
    packaging: 'Kühl, dunkel, trocken und luftig lagern (Netz, Papiertüte oder geflochten), nicht in Plastik.',
    packaging_en: 'Store cool, dark, dry and airy (net, paper bag or braided), not in plastic.',
    reason: 'Im Kühlschrank treibt Knoblauch durch den Kältereiz (Vernalisierung) schneller aus und wird bitterer. Bei Raumtemperatur, trocken und dunkel unter 18 °C hält er sich am längsten. Bereits geschälte oder angeschnittene Zehen dagegen im Kühlschrank lagern.',
    reason_en: 'In the fridge, the cold triggers garlic to sprout faster (vernalization) and turn more bitter. It keeps longest at room temperature, dry and dark, below 18 °C/64 °F. Peeled or cut cloves, however, should go in the fridge.',
  },
  {
    keys: ['champignon', 'champignons', 'pilze', 'pilz'],
    label: 'Champignons', label_en: 'Mushrooms',
    category: 'gemuese',
    emoji: '🍄',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'low',
    packaging: 'In einer Papiertüte im Kühlschrank (nicht im Gemüsefach, dort zu feucht), nicht in geschlossener Plastikverpackung.',
    packaging_en: 'In a paper bag in the fridge (not the crisper drawer, too humid there), not in sealed plastic.',
    reason: 'Pilze bestehen zu großen Teilen aus Wasser und brauchen Luftzirkulation – in geschlossener Plastikverpackung werden sie schnell schleimig. Die Papiertüte nimmt überschüssige Feuchtigkeit auf; so halten sie sich 7-10 Tage.',
    reason_en: 'Mushrooms are mostly water and need air circulation – in sealed plastic they turn slimy fast. The paper bag absorbs excess moisture; this way they keep for 7-10 days.',
  },
  {
    keys: ['spinat'],
    label: 'Spinat', label_en: 'Spinach',
    category: 'gemuese',
    emoji: '🍃',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'high',
    packaging: 'Im Kühlschrank in luftdurchlässiger Verpackung mit etwas Küchenpapier (nimmt Feuchtigkeit auf), nicht neben Obst lagern.',
    packaging_en: 'In the fridge in breathable packaging with some kitchen paper (absorbs moisture), don’t store next to fruit.',
    reason: 'Reagiert extrem empfindlich auf Ethylen – schon geringste Mengen lassen die Blätter binnen 24-48 Stunden gelb werden und schneller welken. Getrennt von Äpfeln, Bananen, Tomaten & Co. lagern.',
    reason_en: 'Extremely ethylene-sensitive – even tiny amounts turn the leaves yellow and wilted within 24-48 hours. Store away from apples, bananas, tomatoes & co.',
  },
  {
    keys: ['zucchini'],
    label: 'Zucchini', label_en: 'Zucchini',
    category: 'gemuese',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'Lose oder in perforierter Tüte im Gemüsefach lagern, nicht ganz hinten/unten im Kühlschrank (dort zu kalt).',
    packaging_en: 'Store loose or in a perforated bag in the crisper drawer, not at the very back/bottom of the fridge (too cold there).',
    reason: 'Unterhalb von ca. 10 °C drohen Kälteschäden (Grübchen, wässrig-mehlige Konsistenz) – daher im wärmeren Gemüsefach lagern. Für den kurzfristigen Verbrauch (1-2 Tage) reicht auch Raumtemperatur.',
    reason_en: 'Below about 10 °C/50 °F, chill damage can occur (pitting, watery-mealy texture) – so store in the warmer crisper drawer. For short-term use (1-2 days), room temperature is also fine.',
  },
  {
    keys: ['aubergine', 'auberginen'],
    label: 'Aubergine', label_en: 'Eggplant',
    category: 'gemuese',
    emoji: '🍆',
    storage: 'both',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'Kühl bei ca. 10-12 °C lagern (Gemüsefach oder kühler Raum), nicht ganz hinten im Kühlschrank.',
    packaging_en: 'Store cool at about 10-12 °C/50-54 °F (crisper drawer or a cool room), not at the very back of the fridge.',
    reason: 'Optimal sind 10-12 °C – wärmer als die meisten Kühlschränke. Unterhalb von ca. 7 °C drohen Kälteschäden (braune Flecken, Bitterkeit, schnelleres Weichwerden). Für 2-4 Tage reicht Raumtemperatur.',
    reason_en: 'Optimal is 10-12 °C/50-54 °F – warmer than most fridges. Below about 7 °C/45 °F, chill damage can occur (brown spots, bitterness, softening faster). Room temperature is fine for 2-4 days.',
  },
  {
    keys: ['orange', 'orangen'],
    label: 'Orange', label_en: 'Orange',
    category: 'obst',
    emoji: '🍊',
    storage: 'both',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'low',
    packaging: 'Ungewaschen, lose oder in perforierter Tüte im Gemüsefach lagern, nicht luftdicht verpacken.',
    packaging_en: 'Store unwashed, loose or in a perforated bag in the crisper drawer, don’t seal airtight.',
    reason: 'Bei Raumtemperatur ca. 5-7 Tage haltbar, im Kühlschrank (Gemüsefach) bis zu 3-4 Wochen. Vor dem Lagern nicht waschen – Feuchtigkeit auf der Schale fördert Schimmelbildung.',
    reason_en: 'Keeps about 5-7 days at room temperature, up to 3-4 weeks in the fridge (crisper drawer). Don’t wash before storing – moisture on the peel promotes mold.',
  },
  {
    keys: ['weintraube', 'weintrauben', 'traube', 'trauben'],
    label: 'Weintrauben', label_en: 'Grapes',
    category: 'obst',
    emoji: '🍇',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'Ungewaschen, lose oder in der Originalverpackung mit Luftlöchern im Kühlschrank, nicht luftdicht.',
    packaging_en: 'Store unwashed, loose or in the original perforated packaging in the fridge, not airtight.',
    reason: 'Im Kühlschrank 1-3 Wochen haltbar, bei Raumtemperatur verderben sie deutlich schneller. Reagieren empfindlich auf Ethylen – nicht direkt neben Äpfeln, Bananen oder Tomaten lagern. Vor dem Lagern nicht waschen, das fördert Schimmel.',
    reason_en: 'Keeps 1-3 weeks in the fridge; spoils much faster at room temperature. Sensitive to ethylene – don’t store directly next to apples, bananas or tomatoes. Don’t wash before storing, that promotes mold.',
  },
  {
    keys: ['birne', 'birnen'],
    label: 'Birne', label_en: 'Pear',
    category: 'obst',
    emoji: '🍐',
    storage: 'both',
    ethyleneProduces: 'high',
    ethyleneSensitive: 'medium',
    packaging: 'Zum Nachreifen bei Raumtemperatur lagern (ggf. in Papiertüte mit Apfel/Banane), reif dann im Kühlschrank weiterlagern.',
    packaging_en: 'To ripen, store at room temperature (optionally in a paper bag with an apple/banana); once ripe, keep in the fridge.',
    reason: 'Birnen reifen nach der Ernte nach – bei Raumtemperatur binnen 3-10 Tagen. Sobald reif (leichter Druck am Stielansatz spürbar), im Kühlschrank lagern, um die weitere Reifung zu verlangsamen. Setzen selbst viel Ethylen frei.',
    reason_en: 'Pears continue ripening after harvest – within 3-10 days at room temperature. Once ripe (slight give near the stem), store in the fridge to slow further ripening. They release a lot of ethylene themselves.',
  },
  {
    keys: ['erdbeere', 'erdbeeren'],
    label: 'Erdbeeren', label_en: 'Strawberries',
    category: 'obst',
    emoji: '🍓',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'high',
    packaging: 'Ungewaschen in einem luftigen/perforierten Behälter mit Küchenpapier im Kühlschrank; erst kurz vor dem Verzehr waschen.',
    packaging_en: 'Store unwashed in an airy/perforated container with kitchen paper in the fridge; wash only right before eating.',
    reason: 'Reagieren sehr empfindlich auf Ethylen und verderben in dessen Nähe deutlich schneller – getrennt von Äpfeln, Bananen & Co. lagern. Waschen vor der Lagerung beschleunigt durch die dünne, durchlässige Schale das Verderben.',
    reason_en: 'Very ethylene-sensitive and spoil much faster near it – store away from apples, bananas & co. Washing before storage speeds up spoiling because of the thin, permeable skin.',
  },
  {
    keys: ['sellerie', 'staudensellerie'],
    label: 'Sellerie', label_en: 'Celery',
    category: 'gemuese',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'In Alufolie eingewickelt (statt Plastiktüte) im Gemüsefach lagern – lässt entstehendes Ethylen entweichen.',
    packaging_en: 'Wrap in aluminum foil (instead of a plastic bag) and store in the crisper drawer – lets the ethylene it produces escape.',
    reason: 'In geschlossener Plastiktüte staut sich das vom Sellerie selbst freigesetzte Ethylen und lässt ihn schneller welk werden. In Alufolie eingewickelt bleibt er 2-3 Wochen knackig.',
    reason_en: 'In a sealed plastic bag, the ethylene celery releases itself builds up and makes it wilt faster. Wrapped in foil, it stays crisp for 2-3 weeks.',
  },
  {
    // Vor "Lauch" einsortiert: "Schnittlauch" enthält "lauch" als Substring,
    // ohne diese Reihenfolge würde produceRule() (erster Treffer gewinnt)
    // fälschlich die Lauch-Regel liefern statt der spezifischeren.
    keys: ['schnittlauch'],
    label: 'Schnittlauch', label_en: 'Chives',
    category: 'kraeuter',
    emoji: '🌱',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'medium',
    packaging: 'In feuchtes Küchenpapier gewickelt in einer Tüte im Kühlschrank, oder wie Schnittblumen mit den Stielen in einem Glas Wasser.',
    packaging_en: 'Wrapped in damp kitchen paper in a bag in the fridge, or like cut flowers with the stems in a glass of water.',
    reason: 'Hält sich feucht gelagert im Kühlschrank etwa eine Woche. Anders als Basilikum verträgt Schnittlauch Kälte gut; für längere Haltbarkeit lässt er sich zudem sehr gut klein geschnitten einfrieren.',
    reason_en: 'Kept moist, it lasts about a week in the fridge. Unlike basil, chives tolerate cold well; for longer storage, they also freeze very well when chopped.',
  },
  {
    keys: ['lauch', 'porree'],
    label: 'Lauch', label_en: 'Leek',
    category: 'gemuese',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'Ungewaschen in perforierter Tüte im Gemüsefach lagern.',
    packaging_en: 'Store unwashed in a perforated bag in the crisper drawer.',
    reason: 'Im Kühlschrank hält sich Lauch bis zu zwei Wochen, bei Raumtemperatur nur wenige Tage. Ungewaschen und mit Wurzelansatz gelagert hält er sich am längsten.',
    reason_en: 'Leek keeps up to two weeks in the fridge, only a few days at room temperature. It keeps longest stored unwashed with the root end intact.',
  },
  {
    keys: ['rote bete', 'rote beete', 'rohe bete', 'bete'],
    label: 'Rote Bete', label_en: 'Beetroot',
    category: 'gemuese',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'low',
    packaging: 'Grün entfernen (entzieht sonst Feuchtigkeit), ungewaschen in perforierter Tüte im Gemüsefach lagern.',
    packaging_en: 'Remove the greens (they draw out moisture otherwise), store unwashed in a perforated bag in the crisper drawer.',
    reason: 'Ohne Grün hält sich Rote Bete im Kühlschrank 2-3 Wochen; das Blattgrün entzieht der Knolle sonst Feuchtigkeit. Vor der Lagerung nicht waschen, nur Erde abbürsten.',
    reason_en: 'Without the greens, beetroot keeps 2-3 weeks in the fridge; the leaves otherwise draw moisture out of the root. Don’t wash before storing, just brush off the soil.',
  },
  {
    keys: ['brokkoli', 'broccoli'],
    label: 'Brokkoli', label_en: 'Broccoli',
    category: 'gemuese',
    emoji: '🥦',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'high',
    packaging: 'Unverpackt oder in perforierter Tüte im Gemüsefach lagern, nicht luftdicht.',
    packaging_en: 'Store unwrapped or in a perforated bag in the crisper drawer, not airtight.',
    reason: 'Sehr ethylenempfindlich und stark atmungsaktiv – bei Raumtemperatur wird er binnen Stunden gelb und welk. Im Kühlschrank hält er sich 3-5 Tage, getrennt von Äpfeln, Bananen & Co.',
    reason_en: 'Very ethylene-sensitive and has a high respiration rate – turns yellow and limp within hours at room temperature. Keeps 3-5 days in the fridge, away from apples, bananas & co.',
  },
  {
    keys: ['blumenkohl'],
    label: 'Blumenkohl', label_en: 'Cauliflower',
    category: 'gemuese',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'Kopf nach unten oder locker in perforierter Tüte im Gemüsefach lagern.',
    packaging_en: 'Store head-down or loosely in a perforated bag in the crisper drawer.',
    reason: 'Hält sich im Kühlschrank etwa eine Woche; Röschen verfärben sich bei Ethylen-Kontakt bräunlich. Kopf-nach-unten-Lagerung verhindert, dass sich Feuchtigkeit in den Röschen sammelt und sie schneller verderben lässt.',
    reason_en: 'Keeps about a week in the fridge; florets brown when exposed to ethylene. Storing head-down keeps moisture from pooling in the florets, which would otherwise speed up spoilage.',
  },
  {
    keys: ['limette', 'limetten'],
    label: 'Limette', label_en: 'Lime',
    category: 'obst',
    storage: 'both',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'low',
    packaging: 'Unverpackt lagerbar. Im Kühlschrank (Gemüsefach) am längsten haltbar, bei Raumtemperatur nur für den kurzfristigen Verbrauch.',
    packaging_en: 'Can be stored unwrapped. Keeps longest in the fridge (crisper drawer); at room temperature only for short-term use.',
    reason: 'Bei Raumtemperatur nur etwa eine Woche haltbar (und verliert an Saftigkeit), im Kühlschrank mehrere Wochen. Wie bei anderen Zitrusfrüchten spielt Ethylen nur eine geringe Rolle.',
    reason_en: 'Keeps only about a week at room temperature (and loses juiciness), several weeks in the fridge. As with other citrus fruit, ethylene plays only a minor role.',
  },
  {
    keys: ['kiwi', 'kiwis'],
    label: 'Kiwi', label_en: 'Kiwi',
    category: 'obst',
    emoji: '🥝',
    storage: 'both',
    ethyleneProduces: 'medium',
    ethyleneSensitive: 'high',
    packaging: 'Unreif bei Raumtemperatur (ggf. in Papiertüte mit Apfel/Banane schneller reifen lassen). Reif: im Kühlschrank, das bremst die weitere Reifung.',
    packaging_en: 'Unripe: at room temperature (optionally in a paper bag with an apple/banana to ripen faster). Ripe: in the fridge, which slows further ripening.',
    reason: 'Reift wie eine Birne nach der Ernte nach und reagiert dabei sehr empfindlich auf Ethylen. Reif (leichter Druck spürbar) im Kühlschrank mehrere Wochen haltbar, getrennt von Äpfeln, Bananen & Co. gelagert.',
    reason_en: 'Continues ripening after harvest like a pear and is very ethylene-sensitive while doing so. Once ripe (slight give when pressed), keeps several weeks in the fridge, stored away from apples, bananas & co.',
  },
  {
    keys: ['pfirsich', 'pfirsiche', 'nektarine', 'nektarinen'],
    label: 'Pfirsich', label_en: 'Peach',
    category: 'obst',
    emoji: '🍑',
    storage: 'both',
    ethyleneProduces: 'high',
    ethyleneSensitive: 'medium',
    packaging: 'Unreif bei Raumtemperatur nachreifen lassen (Stielansatz nach unten), reif dann im Kühlschrank weiterlagern.',
    packaging_en: 'Ripen unripe fruit at room temperature (stem side down); once ripe, keep in the fridge.',
    reason: 'Vor der vollen Reife im Kühlschrank gelagert werden Pfirsiche mehlig und geschmacklos (Kälteschaden) – deshalb erst bei Raumtemperatur nachreifen lassen. Setzen dabei selbst viel Ethylen frei, danach im Kühlschrank 3-5 Tage haltbar.',
    reason_en: 'Refrigerated before fully ripe, peaches turn mealy and bland (chill damage) – so ripen at room temperature first. They release a lot of ethylene themselves while doing so; once ripe, they keep 3-5 days in the fridge.',
  },
  {
    keys: ['kürbis', 'kuerbis', 'kürbisse', 'kuerbisse', 'hokkaido', 'butternut'],
    label: 'Kürbis', label_en: 'Squash/pumpkin',
    category: 'gemuese',
    storage: 'room',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'low',
    packaging: 'Ganz: kühl, dunkel, trocken und luftig lagern (kein Kühlschrank nötig). Angeschnitten: mit Frischhaltefolie abgedeckt im Kühlschrank, zügig verbrauchen.',
    packaging_en: 'Whole: store cool, dark, dry and airy (no fridge needed). Cut: cover with film and refrigerate, use promptly.',
    reason: 'Ganze Winterkürbisse (z.B. Hokkaido, Butternut) halten sich dank fester Schale wochen- bis monatelang bei Raumtemperatur. Angeschnitten verderben sie im Kühlschrank dagegen innerhalb weniger Tage.',
    reason_en: 'Whole winter squash (e.g. Hokkaido, butternut) keeps for weeks to months at room temperature thanks to its firm skin. Once cut, however, it spoils within a few days even in the fridge.',
  },
  {
    keys: ['radieschen'],
    label: 'Radieschen', label_en: 'Radish',
    category: 'gemuese',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'medium',
    packaging: 'Grün entfernen (entzieht sonst Feuchtigkeit), in perforierter Tüte oder feuchtem Tuch im Gemüsefach lagern.',
    packaging_en: 'Remove the greens (they draw out moisture otherwise), store in a perforated bag or damp cloth in the crisper drawer.',
    reason: 'Ohne Grün hält sich Radieschen im Kühlschrank 1-2 Wochen; das Blattgrün lässt die Knolle sonst schneller welk und schwammig werden.',
    reason_en: 'Without the greens, radishes keep 1-2 weeks in the fridge; the leaves otherwise make the root turn limp and spongy faster.',
  },
  {
    keys: ['basilikum'],
    label: 'Basilikum', label_en: 'Basil',
    category: 'kraeuter',
    emoji: '🌿',
    storage: 'room',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'Wie Schnittblumen mit den Stielen in einem Glas Wasser bei Raumtemperatur (nicht direkt in der Sonne), Blätter nicht mit Wasser bedecken.',
    packaging_en: 'Like cut flowers, stems in a glass of water at room temperature (not in direct sun), keep the leaves dry.',
    reason: 'Sehr kälteempfindlich – im Kühlschrank werden die Blätter binnen Stunden bis Tagen schwarz und schleimig (Kälteschaden unterhalb von ca. 10 °C). Bei Raumtemperatur im Wasserglas hält es sich dagegen etwa eine Woche.',
    reason_en: 'Very cold-sensitive – in the fridge the leaves turn black and slimy within hours to days (chill damage below about 10 °C/50 °F). In a glass of water at room temperature, however, it keeps for about a week.',
  },
  {
    keys: ['petersilie'],
    label: 'Petersilie', label_en: 'Parsley',
    category: 'kraeuter',
    emoji: '🍃',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'medium',
    packaging: 'Wie Schnittblumen mit den Stielen in einem Glas Wasser im Kühlschrank, oder in feuchtes Küchenpapier gewickelt in einer Tüte.',
    packaging_en: 'Like cut flowers, stems in a glass of water in the fridge, or wrapped in damp kitchen paper in a bag.',
    reason: 'Anders als Basilikum verträgt Petersilie Kälte gut – im Wasserglas oder feuchten Tuch im Kühlschrank hält sie sich 1-2 Wochen, statt nach wenigen Tagen im offenen Beutel zu welken.',
    reason_en: 'Unlike basil, parsley tolerates cold well – in a glass of water or a damp cloth in the fridge it keeps 1-2 weeks, instead of wilting within a few days in an open bag.',
  },
  {
    keys: ['ingwer'],
    label: 'Ingwer', label_en: 'Ginger',
    category: 'gemuese',
    emoji: '🫚',
    storage: 'both',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'low',
    packaging: 'Unangeschnitten: trocken und luftig bei Raumtemperatur, für längere Haltbarkeit in Küchenpapier gewickelt im Kühlschrank. Angeschnitten: im Kühlschrank oder eingefroren.',
    packaging_en: 'Uncut: dry and airy at room temperature; for longer storage, wrap in kitchen paper and refrigerate. Cut: keep in the fridge or freeze.',
    reason: 'Unangeschnitten bei Raumtemperatur etwa 1-2 Wochen haltbar, im Kühlschrank (in Papier gewickelt) mehrere Wochen. Für sehr lange Haltbarkeit lässt sich Ingwer auch unangeschnitten einfrieren und bei Bedarf gerieben werden.',
    reason_en: 'Uncut, it keeps about 1-2 weeks at room temperature, several weeks in the fridge (wrapped in paper). For very long storage, ginger can also be frozen whole and grated straight from frozen when needed.',
  },
  {
    keys: ['mango', 'mangos'],
    label: 'Mango', label_en: 'Mango',
    category: 'obst',
    emoji: '🥭',
    storage: 'both',
    ethyleneProduces: 'high',
    ethyleneSensitive: 'high',
    packaging: 'Unreif bei Raumtemperatur (ggf. in Papiertüte mit Apfel/Banane schneller reifen lassen). Reif: im Kühlschrank, das bremst die weitere Reifung um einige Tage.',
    packaging_en: 'Unripe: at room temperature (optionally in a paper bag with an apple/banana to ripen faster). Ripe: in the fridge, which slows further ripening by a few days.',
    reason: 'Reift wie eine Avocado nach der Ernte nach und reagiert dabei sehr empfindlich auf Ethylen. Unreif im Kühlschrank gelagert reift sie kaum noch nach und bleibt oft dauerhaft faserig-sauer.',
    reason_en: 'Continues ripening after harvest like an avocado and is very ethylene-sensitive while doing so. Refrigerated while still unripe, it barely ripens further and often stays fibrous and sour.',
  },
  {
    keys: ['ananas'],
    label: 'Ananas', label_en: 'Pineapple',
    category: 'obst',
    emoji: '🍍',
    storage: 'both',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'low',
    packaging: 'Ganz: aufrecht bei Raumtemperatur oder im Kühlschrank. Angeschnitten: luftdicht im Kühlschrank, innerhalb weniger Tage verbrauchen.',
    packaging_en: 'Whole: upright at room temperature or in the fridge. Cut: airtight in the fridge, use within a few days.',
    reason: 'Anders als oft angenommen wird eine Ananas nach der Ernte NICHT mehr süßer – der Zuckergehalt ist beim Pflücken bereits festgelegt, nur die Konsistenz wird noch etwas weicher. Ganz hält sie sich bei Raumtemperatur wenige Tage, im Kühlschrank bis zu einer Woche.',
    reason_en: 'Contrary to popular belief, a pineapple does NOT get sweeter after harvest – sugar content is fixed at picking, only the texture softens a bit further. Whole, it keeps a few days at room temperature, up to a week in the fridge.',
  },
  {
    keys: ['kirsche', 'kirschen', 'süßkirsche', 'suesskirsche'],
    label: 'Kirschen', label_en: 'Cherries',
    category: 'obst',
    emoji: '🍒',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'low',
    packaging: 'Ungewaschen in einem luftigen/perforierten Behälter im Kühlschrank; erst kurz vor dem Verzehr waschen.',
    packaging_en: 'Store unwashed in an airy/perforated container in the fridge; wash only right before eating.',
    reason: 'Im Kühlschrank etwa eine Woche haltbar, bei Raumtemperatur verderben sie binnen 1-2 Tagen deutlich schneller. Waschen vor der Lagerung fördert durch die zusätzliche Feuchtigkeit Schimmel.',
    reason_en: 'Keeps about a week in the fridge; spoils noticeably faster within 1-2 days at room temperature. Washing before storage promotes mold due to the added moisture.',
  },
  {
    keys: ['melone', 'wassermelone', 'honigmelone', 'zuckermelone', 'cantaloupe'],
    label: 'Melone', label_en: 'Melon',
    category: 'obst',
    emoji: '🍉',
    storage: 'room',
    ethyleneProduces: 'medium',
    ethyleneSensitive: 'low',
    packaging: 'Ganz: bei Raumtemperatur. Angeschnitten: luftdicht abgedeckt im Kühlschrank, innerhalb weniger Tage verbrauchen.',
    packaging_en: 'Whole: at room temperature. Cut: covered airtight in the fridge, use within a few days.',
    reason: 'Ganz hält sich bei Raumtemperatur etwa eine Woche, im Kühlschrank kaum länger und kostet nur Platz. Einmal angeschnitten dagegen zügig kühlen und innerhalb von 3-4 Tagen aufbrauchen.',
    reason_en: 'Whole, it keeps about a week at room temperature, barely longer in the fridge while taking up space. Once cut, however, refrigerate promptly and use within 3-4 days.',
  },
  {
    keys: ['zuckermais', 'mais', 'maiskolben'],
    label: 'Zuckermais', label_en: 'Sweetcorn',
    category: 'gemuese',
    emoji: '🌽',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'low',
    packaging: 'Ungeschält (mit Lieschblättern) in perforierter Tüte im Kühlschrank lagern.',
    packaging_en: 'Store unhusked (with the husk leaves on) in a perforated bag in the fridge.',
    reason: 'Zucker wandelt sich bei Zuckermais besonders schnell in Stärke um – bei Raumtemperatur verliert er binnen eines Tages spürbar an Süße. Im Kühlschrank verlangsamt sich das deutlich, am besten innerhalb von 1-2 Tagen verbrauchen.',
    reason_en: 'Sweetcorn converts sugar to starch especially fast – at room temperature it noticeably loses sweetness within a day. The fridge slows this down considerably; best used within 1-2 days regardless.',
  },
  {
    keys: ['heidelbeere', 'heidelbeeren', 'blaubeere', 'blaubeeren'],
    label: 'Heidelbeeren', label_en: 'Blueberries',
    category: 'obst',
    emoji: '🫐',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'medium',
    packaging: 'Ungewaschen in einem luftigen/perforierten Behälter im Kühlschrank; erst kurz vor dem Verzehr waschen.',
    packaging_en: 'Store unwashed in an airy/perforated container in the fridge; wash only right before eating.',
    reason: 'Robuster als Erdbeeren, halten sich im Kühlschrank 1-2 Wochen. Waschen vor der Lagerung fördert durch die zusätzliche Feuchtigkeit Schimmel und Weichwerden.',
    reason_en: 'More robust than strawberries, keeping 1-2 weeks in the fridge. Washing before storage promotes mold and softening due to the added moisture.',
  },
  {
    keys: ['kokosnuss', 'kokosnüsse', 'kokosnuesse'],
    label: 'Kokosnuss', label_en: 'Coconut',
    category: 'obst',
    emoji: '🥥',
    storage: 'room',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'none',
    packaging: 'Ganz: kühl und trocken bei Raumtemperatur. Aufgebrochen: Fruchtfleisch luftdicht im Kühlschrank, Kokoswasser separat kühlen und zügig verbrauchen.',
    packaging_en: 'Whole: cool and dry at room temperature. Cracked: keep the flesh airtight in the fridge, refrigerate the water separately and use promptly.',
    reason: 'Die harte Schale schützt das Fruchtfleisch – ganz hält sich eine Kokosnuss bei Raumtemperatur mehrere Wochen bis Monate. Einmal geöffnet verdirbt sie dagegen wie jede andere frische Frucht innerhalb weniger Tage.',
    reason_en: 'The hard shell protects the flesh – whole, a coconut keeps for weeks to months at room temperature. Once opened, it spoils like any other fresh fruit within a few days.',
  },
  {
    keys: ['kohlrabi'],
    label: 'Kohlrabi', label_en: 'Kohlrabi',
    category: 'gemuese',
    storage: 'fridge',
    ethyleneProduces: 'none',
    ethyleneSensitive: 'medium',
    packaging: 'Blätter entfernen (entziehen sonst Feuchtigkeit), in perforierter Tüte im Gemüsefach lagern.',
    packaging_en: 'Remove the leaves (they draw out moisture otherwise), store in a perforated bag in the crisper drawer.',
    reason: 'Ohne Blätter hält sich Kohlrabi im Kühlschrank 1-2 Wochen. Wie andere Kohlgemüse reagiert er empfindlich auf Ethylen aus der Nähe von Äpfeln, Bananen & Co. (wird schneller holzig).',
    reason_en: 'Without the leaves, kohlrabi keeps 1-2 weeks in the fridge. Like other brassicas, it is ethylene-sensitive when stored near apples, bananas & co. (turns woody faster).',
  },
  {
    keys: ['rosenkohl'],
    label: 'Rosenkohl', label_en: 'Brussels sprouts',
    category: 'gemuese',
    storage: 'fridge',
    ethyleneProduces: 'low',
    ethyleneSensitive: 'high',
    packaging: 'Am Stiel: unverpackt im Kühlschrank, hält am längsten. Lose Röschen: in perforierter Tüte im Gemüsefach.',
    packaging_en: 'On the stalk: unwrapped in the fridge, keeps longest. Loose sprouts: in a perforated bag in the crisper drawer.',
    reason: 'Am Stiel gelagert hält sich Rosenkohl bis zu drei Wochen, lose Röschen dagegen nur etwa eine Woche. Sehr ethylenempfindlich – wird in der Nähe von Äpfeln, Bananen & Co. schneller gelb und bitter.',
    reason_en: 'Stored on the stalk, Brussels sprouts keep up to three weeks; loose sprouts only about a week. Very ethylene-sensitive – turns yellow and bitter faster near apples, bananas & co.',
  },
];

// Passende Regel zum Namen (oder null) – erster Substring-Treffer gewinnt.
export function produceRule(name) {
  const n = (name || '').toLowerCase();
  if (!n) return null;
  for (const r of PRODUCE_RULES) {
    if (r.keys.some((k) => n.includes(k))) return r;
  }
  return null;
}

const ETHYLENE_KEYS = { high: 'produce.ethyleneHigh', medium: 'produce.ethyleneMedium', low: 'produce.ethyleneLow', none: 'produce.ethyleneNone' };

export function ethyleneLabel(level, lang = 'de') {
  const key = ETHYLENE_KEYS[level];
  return key ? tr(lang, key) : '—';
}
