// Auftau-Ratgeber: wie taut man was am besten und sicher auf. Ergänzt
// frozenShelfLife.js (das nur "wie lange hält's gefroren" beantwortet) um
// die Frage "wie komme ich sicher wieder raus". Jeder Eintrag ist recherchiert
// (u.a. USDA FSIS, BVL Lebensmittelhygiene, Verbraucherzentrale-nahe Quellen)
// - keine erfundenen Angaben.
//
// Gleiches Matching-Muster wie die anderen *ShelfLife.js-Dateien: erster
// Substring-Treffer auf den kleingeschriebenen Namen gewinnt, Spezifisches
// vor Allgemeinem. `category` dient nur der Anzeige/Gruppierung.
//
// `method`: 'fridge' | 'coldWater' | 'microwave' | 'room' | 'direct'
// ('direct' = kein Auftauen nötig, direkt gefroren verarbeiten/erhitzen).

export const THAWING_RULES = [
  { keys: ['hackfleisch', 'hackepeter', 'schabefleisch', 'tatar', 'mett'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Hackfleisch / Mett (roh)', label_en: 'Ground meat (raw)', method: 'fridge', time: '12-24 Std.', time_en: '12-24 hrs', reason: 'Alternativ in kaltem Wasser (Beutel alle 30 Min. wechseln, ca. 1-2 Std.) - niemals bei Raumtemperatur. Nach dem Auftauen sofort verarbeiten, nicht roh erneut einfrieren.', reason_en: 'Alternatively in cold water (change every 30 min, about 1-2 hrs) - never at room temperature. Cook immediately after thawing, do not refreeze raw.' },
  { keys: ['hähnchen', 'haehnchen', 'hühner', 'huhn', 'pute', 'geflügel', 'gefluegel'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Geflügel (roh)', label_en: 'Poultry (raw)', method: 'fridge', time: '24-48 Std. (je nach Größe)', time_en: '24-48 hrs (depending on size)', reason: 'Wegen Salmonellen-Risiko niemals bei Raumtemperatur auftauen. Sofort nach dem Auftauen garen, nicht roh erneut einfrieren.', reason_en: 'Due to salmonella risk, never thaw at room temperature. Cook immediately after thawing, do not refreeze raw.' },
  { keys: ['schnitzel', 'gulasch', 'steak', 'filet', 'kotelett', 'braten', 'rinderbraten', 'schweinebraten', 'fleisch'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Rotes Fleisch (roh, Braten/Steak)', label_en: 'Red meat (raw, roast/steak)', method: 'fridge', time: '12-24 Std. pro kg', time_en: '12-24 hrs per kg', reason: 'Alternativ in kaltem Wasser, deutlich schneller. Nicht bei Raumtemperatur auftauen, nach dem Auftauen zeitnah verarbeiten.', reason_en: 'Alternatively in cold water, much faster. Do not thaw at room temperature, use promptly after thawing.' },
  { keys: ['aufschnitt', 'lyoner', 'mortadella', 'fleischwurst', 'bierschinken', 'kochschinken', 'gelbwurst', 'wiener', 'würstchen', 'wuerstchen', 'frankfurter', 'saitenwurst', 'schinken', 'salami', 'dauerwurst', 'cervelat', 'landjäger', 'landjaeger', 'chorizo', 'pepperoni', 'speck', 'bacon', 'rohschinken', 'serrano', 'parma', 'prosciutto', 'wurst'], category: 'Fleisch & Wurst', category_en: 'Meat & Sausage', label: 'Aufschnitt / Wurst', label_en: 'Cold cuts / sausage', method: 'fridge', time: 'einige Std. bis über Nacht', time_en: 'a few hrs to overnight', reason: 'Dünne Scheiben oft schon nach kurzer Zeit verwendbar. Nach dem Auftauen zügig aufbrauchen.', reason_en: 'Thin slices are often usable after a short time. Use up promptly after thawing.' },
  { keys: ['lachs', 'hering', 'makrele', 'thunfisch', 'thun', 'kabeljau', 'seelachs', 'scholle', 'zander', 'forelle', 'pangasius', 'fisch'], category: 'Fisch & Meeresfrüchte', category_en: 'Fish & Seafood', label: 'Fisch', label_en: 'Fish', method: 'fridge', time: '6-24 Std. (je nach Größe/Form)', time_en: '6-24 hrs (depending on size/shape)', reason: 'Am schonendsten im Kühlschrank; alternativ in kaltem Wasser (alle 30 Min. wechseln), dann meist nach ca. 1 Std. fertig. Nicht bei Raumtemperatur auftauen.', reason_en: 'Gentlest in the fridge; alternatively in cold water (change every 30 min), usually ready after about 1 hr. Do not thaw at room temperature.' },
  { keys: ['parmesan', 'grana', 'pecorino', 'bergkäse', 'hartkäse', 'emmentaler', 'gouda', 'cheddar', 'edamer', 'tilsiter', 'butterkäse', 'maasdamer', 'appenzeller', 'raclette', 'käse', 'kaese'], category: 'Käse', category_en: 'Cheese', label: 'Hart- / Schnittkäse', label_en: 'Hard / semi-hard cheese', method: 'fridge', time: 'einige Std.', time_en: 'a few hrs', reason: 'Langsam im Kühlschrank auftauen, damit möglichst wenig Feuchtigkeit austritt.', reason_en: 'Thaw slowly in the fridge so as little moisture as possible is lost.' },
  { keys: ['butter', 'margarine'], category: 'Fette & Eier', category_en: 'Fats & Eggs', label: 'Butter / Margarine', label_en: 'Butter / margarine', method: 'fridge', time: 'einige Std.', time_en: 'a few hrs', reason: 'Alternativ portionsweise bei Raumtemperatur (ca. 30-60 Min.).', reason_en: 'Alternatively in portions at room temperature (about 30-60 min).' },
  { keys: ['sahne', 'obers'], category: 'Milchprodukte', category_en: 'Dairy', label: 'Sahne', label_en: 'Cream', method: 'fridge', time: 'über Nacht', time_en: 'overnight', reason: 'Nach dem Auftauen gut verrühren oder erneut aufschlagen, da sich die Konsistenz leicht verändert.', reason_en: 'Stir well or re-whip after thawing, since the consistency changes slightly.' },
  { keys: ['frischmilch', 'vollmilch', 'h-milch', 'milch'], category: 'Milchprodukte', category_en: 'Dairy', label: 'Milch', label_en: 'Milk', method: 'fridge', time: 'über Nacht', time_en: 'overnight', reason: 'Nach dem Auftauen gut schütteln, da sich Fett und Wasser getrennt haben - am besten nur zum Kochen verwenden.', reason_en: 'Shake well after thawing, since fat and water have separated - best used only for cooking.' },
  { keys: ['brot', 'toast', 'brötchen', 'broetchen', 'baguette'], category: 'Backwaren & Teig', category_en: 'Baked Goods & Dough', label: 'Brot / Backwaren', label_en: 'Bread / baked goods', method: 'room', time: '10-20 Min. (aufgeschnitten)', time_en: '10-20 min (sliced)', reason: 'Ein ganzer Laib taut im Ofen bei ca. 50 °C Umluft in ca. 20 Min. gleichmäßiger auf. Brötchen/Toast lassen sich auch direkt aus der Truhe toasten.', reason_en: 'A whole loaf thaws more evenly in the oven at about 50 °C fan in about 20 min. Rolls/toast can also be toasted directly from frozen.' },
  { keys: ['hefeteig'], category: 'Backwaren & Teig', category_en: 'Baked Goods & Dough', label: 'Hefeteig (roh)', label_en: 'Yeast dough (raw)', method: 'fridge', time: 'über Nacht (oder 2-3 Std. bei Raumtemperatur)', time_en: 'overnight (or 2-3 hrs at room temperature)', reason: 'Langsames Auftauen im Kühlschrank schont die Hefe am meisten.', reason_en: 'Slow thawing in the fridge is gentlest on the yeast.' },
  { keys: ['blätterteig', 'blaetterteig', 'pizzateig'], category: 'Backwaren & Teig', category_en: 'Baked Goods & Dough', label: 'Blätterteig / Pizzateig', label_en: 'Puff pastry / pizza dough', method: 'fridge', time: '2-3 Std., danach 30-60 Min. bei Raumtemperatur', time_en: '2-3 hrs, then 30-60 min at room temperature', reason: 'Fertiger Blätterteig lässt sich auch direkt aus der Truhe in Ofen/Mikrowelle verarbeiten (ca. 5-10 Min. bei ca. 150 °C).', reason_en: 'Store-bought puff pastry can also go straight from frozen into the oven/microwave (about 5-10 min at around 150 °C).' },
  { keys: ['erbsen', 'bohnen', 'brokkoli', 'blumenkohl', 'spinat', 'möhre', 'moehre', 'karotte', 'karotten', 'fenchel', 'kohlrabi', 'mangold', 'rosenkohl', 'zucchini', 'paprika', 'pilz', 'champignon', 'spargel', 'kürbis', 'kuerbis', 'lauchzwiebel', 'gemüse', 'gemuese'], category: 'Obst & Gemüse', category_en: 'Fruit & Vegetables', label: 'Gemüse', label_en: 'Vegetables', method: 'direct', time: 'kein Auftauen nötig', time_en: 'no thawing needed', reason: 'Direkt gefroren in kochendes Wasser oder die heiße Pfanne geben - separates Auftauen macht es nur matschig.', reason_en: 'Add straight from frozen into boiling water or a hot pan - separate thawing just makes it mushy.' },
  { keys: ['beere', 'beeren', 'himbeere', 'himbeeren', 'heidelbeere', 'heidelbeeren', 'blaubeere', 'blaubeeren', 'erdbeere', 'erdbeeren', 'kirsche', 'kirschen', 'pfirsich', 'aprikose', 'apfel', 'äpfel', 'aepfel', 'birne', 'birnen', 'banane', 'bananen', 'obst'], category: 'Obst & Gemüse', category_en: 'Fruit & Vegetables', label: 'Obst / Beeren', label_en: 'Fruit / berries', method: 'direct', time: 'je nach Verwendung', time_en: 'depending on use', reason: 'Für Smoothies/Backen direkt gefroren verwenden; soll es "aufgetaut" verzehrt werden, reichen 2-4 Std. im Kühlschrank.', reason_en: 'Use straight from frozen for smoothies/baking; if it should be eaten "thawed," 2-4 hrs in the fridge is enough.' },
  { keys: ['suppe', 'eintopf', 'auflauf', 'fertiggericht', 'reste', 'soße', 'sosse', 'sauce', 'pasta', 'nudelgericht'], category: 'Fertiggerichte & Reste', category_en: 'Ready Meals & Leftovers', label: 'Reste / gekochte Gerichte', label_en: 'Leftovers / cooked dishes', method: 'microwave', time: 'direkt erhitzen', time_en: 'heat directly', reason: 'Meist kein separates Auftauen nötig - direkt aus der Truhe in Mikrowelle oder Ofen erhitzen. Alternativ über Nacht im Kühlschrank auftauen.', reason_en: 'Usually no separate thawing needed - heat straight from frozen in the microwave or oven. Alternatively thaw overnight in the fridge.' },
];

// Passende Regel zum Namen (oder null) – erster Substring-Treffer gewinnt.
export function thawRule(name) {
  const n = (name || '').toLowerCase();
  if (!n) return null;
  for (const r of THAWING_RULES) {
    if (r.keys.some((k) => n.includes(k))) return r;
  }
  return null;
}

// Info-Objekt für die Anzeige: { method, time, reason, label, time_en, reason_en, label_en } | null.
export function thawInfo(name) {
  const r = thawRule(name);
  if (!r) return null;
  return { method: r.method, time: r.time, reason: r.reason, label: r.label, time_en: r.time_en, reason_en: r.reason_en, label_en: r.label_en };
}
